version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5555:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
volumes:
  pgdata:
